// design-sync prestep — build the converter's entry from dist/, with
// motely-wasm's .NET runtime swapped for a data-only slice.
//
// WHY: jaml-ui's vite build externalizes `motely-wasm`. The design-sync
// converter bundles dist/ for the browser, follows that bare import into
// node_modules, and dies on motely-wasm's dotnet.js runtime loader, which
// probes `node:process` / `node:module` behind webpackIgnore'd dynamic
// imports esbuild doesn't honor ([UNRESOLVED_IMPORT]).
//
// WHAT jaml-ui actually needs from motely-wasm at render time is the
// generated game DATA — MotelyTag, MotelyDeck, MotelyItemEdition, … — which
// all live in dist/generated/modules/index.g.mjs, a module whose import
// graph never touches dotnet.js (verified: dotnet importers are only
// boot.mjs / config.mjs / index.mjs). The bootsharp DEFAULT export is the
// runtime bootstrapper; inside a Claude Design preview there is no WASM to
// boot, so it becomes an inert stub that throws a clear message if reached.
//
// This script is COMMITTED and runs from cfg.buildCmd after `pnpm build`,
// so the patched copy is regenerated from a fresh dist/ on every sync —
// never hand-edited, never stale.
import { cpSync, rmSync, writeFileSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "dist");
const out = join(root, ".design-sync", ".cache", "ds-dist");

rmSync(out, { recursive: true, force: true });
cpSync(src, out, { recursive: true });

const LITE = join(out, "motely-lite.mjs");
writeFileSync(
  LITE,
  `// AUTO-GENERATED by make-ds-dist.mjs — data-only motely-wasm for design previews.
// Named exports: the real generated game data (enums, decoders, interop
// class shells) — a dotnet-free subtree of the actual package, so Jamlyzer
// components render true names/sprites. Path import bypasses the package's
// exports map on purpose.
export * from ${JSON.stringify(relative(dirname(LITE), join(root, "node_modules", "motely-wasm", "dist", "generated", "modules", "index.g.mjs")).replace(/\\/g, "/"))};
// Default export: bootsharp's slot. Booting the .NET runtime is impossible
// inside a design preview iframe; anything that reaches for it gets a clear
// error instead of a hang.
export default {
  boot: async () => { throw new Error("motely-wasm runtime is unavailable in design previews - components render from props here"); },
  exit: async () => {},
  resources: {},
};
`,
);

// Rewrite every `from "motely-wasm"` in the copy to the lite module,
// relative to the importing file. dist has no subpath imports (verified);
// the bare specifier is the only form present.
//
// ALSO inline every `new URL("../assets/<file>", import.meta.url).href` as a
// data: URI. The design bundle is an iife whose `import.meta.url` is a
// synthetic constant (https://ds-preview.invalid/), so those URLs resolve to
// a host that cannot exist — measured result: DeckSprite and every other
// sprite-bearing component rendered COMPLETELY BLANK in previews, and would
// in every real design too. ~1.3MB of PNGs becomes ~1.75MB of base64 inside
// the bundle — self-contained beats small here, and it stays far under the
// upload's 12MB per-file cap. (npm consumers keep the file-URL form; this
// only patches the design-sync copy.)
const MIME = { ".png": "image/png", ".ttf": "font/ttf", ".woff2": "font/woff2", ".svg": "image/svg+xml" };
const URL_REF = /new URL\("([^"]*assets\/[^"]+)",\s*import\.meta\.url\)\.href/g;
let patched = 0;
let inlined = 0;
const walk = (dir) => {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) { walk(p); continue; }
    if (!/\.(js|mjs)$/.test(name)) continue;
    const before = readFileSync(p, "utf8");
    const rel = relative(dirname(p), LITE).replace(/\\/g, "/");
    const spec = rel.startsWith(".") ? rel : "./" + rel;
    let after = before.replaceAll('"motely-wasm"', JSON.stringify(spec));
    after = after.replace(URL_REF, (whole, assetRel) => {
      const assetPath = join(dirname(p), assetRel);
      const ext = assetRel.slice(assetRel.lastIndexOf("."));
      if (!MIME[ext] || !statSync(assetPath, { throwIfNoEntry: false })) return whole;
      inlined++;
      return JSON.stringify(`data:${MIME[ext]};base64,${readFileSync(assetPath).toString("base64")}`);
    });
    if (after !== before) { writeFileSync(p, after); patched++; }
  }
};
walk(out);
console.log(`ds-dist ready: ${out} (${patched} file(s) patched, ${inlined} asset URL(s) inlined as data URIs)`);
