export const MOTELY_ITEM_FORMATS_BY_VALUE = Object.freeze({
  4096: Object.freeze({ value: 4096, enumName: "TwoOfClubs", displayName: "2 of Clubs", category: "Standardcard" }),
  4097: Object.freeze({ value: 4097, enumName: "ThreeOfClubs", displayName: "3 of Clubs", category: "Standardcard" }),
  4098: Object.freeze({ value: 4098, enumName: "FourOfClubs", displayName: "4 of Clubs", category: "Standardcard" }),
  4099: Object.freeze({ value: 4099, enumName: "FiveOfClubs", displayName: "5 of Clubs", category: "Standardcard" }),
  4100: Object.freeze({ value: 4100, enumName: "SixOfClubs", displayName: "6 of Clubs", category: "Standardcard" }),
  4101: Object.freeze({ value: 4101, enumName: "SevenOfClubs", displayName: "7 of Clubs", category: "Standardcard" }),
  4102: Object.freeze({ value: 4102, enumName: "EightOfClubs", displayName: "8 of Clubs", category: "Standardcard" }),
  4103: Object.freeze({ value: 4103, enumName: "NineOfClubs", displayName: "9 of Clubs", category: "Standardcard" }),
  4104: Object.freeze({ value: 4104, enumName: "TenOfClubs", displayName: "10 of Clubs", category: "Standardcard" }),
  4105: Object.freeze({ value: 4105, enumName: "JackOfClubs", displayName: "Jack of Clubs", category: "Standardcard" }),
  4106: Object.freeze({ value: 4106, enumName: "QueenOfClubs", displayName: "Queen of Clubs", category: "Standardcard" }),
  4107: Object.freeze({ value: 4107, enumName: "KingOfClubs", displayName: "King of Clubs", category: "Standardcard" }),
  4108: Object.freeze({ value: 4108, enumName: "AceOfClubs", displayName: "Ace of Clubs", category: "Standardcard" }),
  4112: Object.freeze({ value: 4112, enumName: "TwoOfDiamonds", displayName: "2 of Diamonds", category: "Standardcard" }),
  4113: Object.freeze({ value: 4113, enumName: "ThreeOfDiamonds", displayName: "3 of Diamonds", category: "Standardcard" }),
  4114: Object.freeze({ value: 4114, enumName: "FourOfDiamonds", displayName: "4 of Diamonds", category: "Standardcard" }),
  4115: Object.freeze({ value: 4115, enumName: "FiveOfDiamonds", displayName: "5 of Diamonds", category: "Standardcard" }),
  4116: Object.freeze({ value: 4116, enumName: "SixOfDiamonds", displayName: "6 of Diamonds", category: "Standardcard" }),
  4117: Object.freeze({ value: 4117, enumName: "SevenOfDiamonds", displayName: "7 of Diamonds", category: "Standardcard" }),
  4118: Object.freeze({ value: 4118, enumName: "EightOfDiamonds", displayName: "8 of Diamonds", category: "Standardcard" }),
  4119: Object.freeze({ value: 4119, enumName: "NineOfDiamonds", displayName: "9 of Diamonds", category: "Standardcard" }),
  4120: Object.freeze({ value: 4120, enumName: "TenOfDiamonds", displayName: "10 of Diamonds", category: "Standardcard" }),
  4121: Object.freeze({ value: 4121, enumName: "JackOfDiamonds", displayName: "Jack of Diamonds", category: "Standardcard" }),
  4122: Object.freeze({ value: 4122, enumName: "QueenOfDiamonds", displayName: "Queen of Diamonds", category: "Standardcard" }),
  4123: Object.freeze({ value: 4123, enumName: "KingOfDiamonds", displayName: "King of Diamonds", category: "Standardcard" }),
  4124: Object.freeze({ value: 4124, enumName: "AceOfDiamonds", displayName: "Ace of Diamonds", category: "Standardcard" }),
  4128: Object.freeze({ value: 4128, enumName: "TwoOfHearts", displayName: "2 of Hearts", category: "Standardcard" }),
  4129: Object.freeze({ value: 4129, enumName: "ThreeOfHearts", displayName: "3 of Hearts", category: "Standardcard" }),
  4130: Object.freeze({ value: 4130, enumName: "FourOfHearts", displayName: "4 of Hearts", category: "Standardcard" }),
  4131: Object.freeze({ value: 4131, enumName: "FiveOfHearts", displayName: "5 of Hearts", category: "Standardcard" }),
  4132: Object.freeze({ value: 4132, enumName: "SixOfHearts", displayName: "6 of Hearts", category: "Standardcard" }),
  4133: Object.freeze({ value: 4133, enumName: "SevenOfHearts", displayName: "7 of Hearts", category: "Standardcard" }),
  4134: Object.freeze({ value: 4134, enumName: "EightOfHearts", displayName: "8 of Hearts", category: "Standardcard" }),
  4135: Object.freeze({ value: 4135, enumName: "NineOfHearts", displayName: "9 of Hearts", category: "Standardcard" }),
  4136: Object.freeze({ value: 4136, enumName: "TenOfHearts", displayName: "10 of Hearts", category: "Standardcard" }),
  4137: Object.freeze({ value: 4137, enumName: "JackOfHearts", displayName: "Jack of Hearts", category: "Standardcard" }),
  4138: Object.freeze({ value: 4138, enumName: "QueenOfHearts", displayName: "Queen of Hearts", category: "Standardcard" }),
  4139: Object.freeze({ value: 4139, enumName: "KingOfHearts", displayName: "King of Hearts", category: "Standardcard" }),
  4140: Object.freeze({ value: 4140, enumName: "AceOfHearts", displayName: "Ace of Hearts", category: "Standardcard" }),
  4144: Object.freeze({ value: 4144, enumName: "TwoOfSpades", displayName: "2 of Spades", category: "Standardcard" }),
  4145: Object.freeze({ value: 4145, enumName: "ThreeOfSpades", displayName: "3 of Spades", category: "Standardcard" }),
  4146: Object.freeze({ value: 4146, enumName: "FourOfSpades", displayName: "4 of Spades", category: "Standardcard" }),
  4147: Object.freeze({ value: 4147, enumName: "FiveOfSpades", displayName: "5 of Spades", category: "Standardcard" }),
  4148: Object.freeze({ value: 4148, enumName: "SixOfSpades", displayName: "6 of Spades", category: "Standardcard" }),
  4149: Object.freeze({ value: 4149, enumName: "SevenOfSpades", displayName: "7 of Spades", category: "Standardcard" }),
  4150: Object.freeze({ value: 4150, enumName: "EightOfSpades", displayName: "8 of Spades", category: "Standardcard" }),
  4151: Object.freeze({ value: 4151, enumName: "NineOfSpades", displayName: "9 of Spades", category: "Standardcard" }),
  4152: Object.freeze({ value: 4152, enumName: "TenOfSpades", displayName: "10 of Spades", category: "Standardcard" }),
  4153: Object.freeze({ value: 4153, enumName: "JackOfSpades", displayName: "Jack of Spades", category: "Standardcard" }),
  4154: Object.freeze({ value: 4154, enumName: "QueenOfSpades", displayName: "Queen of Spades", category: "Standardcard" }),
  4155: Object.freeze({ value: 4155, enumName: "KingOfSpades", displayName: "King of Spades", category: "Standardcard" }),
  4156: Object.freeze({ value: 4156, enumName: "AceOfSpades", displayName: "Ace of Spades", category: "Standardcard" }),
  8192: Object.freeze({ value: 8192, enumName: "Familiar", displayName: "Familiar", category: "SpectralCard" }),
  8193: Object.freeze({ value: 8193, enumName: "Grim", displayName: "Grim", category: "SpectralCard" }),
  8194: Object.freeze({ value: 8194, enumName: "Incantation", displayName: "Incantation", category: "SpectralCard" }),
  8195: Object.freeze({ value: 8195, enumName: "Talisman", displayName: "Talisman", category: "SpectralCard" }),
  8196: Object.freeze({ value: 8196, enumName: "Aura", displayName: "Aura", category: "SpectralCard" }),
  8197: Object.freeze({ value: 8197, enumName: "Wraith", displayName: "Wraith", category: "SpectralCard" }),
  8198: Object.freeze({ value: 8198, enumName: "Sigil", displayName: "Sigil", category: "SpectralCard" }),
  8199: Object.freeze({ value: 8199, enumName: "Ouija", displayName: "Ouija", category: "SpectralCard" }),
  8200: Object.freeze({ value: 8200, enumName: "Ectoplasm", displayName: "Ectoplasm", category: "SpectralCard" }),
  8201: Object.freeze({ value: 8201, enumName: "Immolate", displayName: "Immolate", category: "SpectralCard" }),
  8202: Object.freeze({ value: 8202, enumName: "Ankh", displayName: "Ankh", category: "SpectralCard" }),
  8203: Object.freeze({ value: 8203, enumName: "DejaVu", displayName: "Deja Vu", category: "SpectralCard" }),
  8204: Object.freeze({ value: 8204, enumName: "Hex", displayName: "Hex", category: "SpectralCard" }),
  8205: Object.freeze({ value: 8205, enumName: "Trance", displayName: "Trance", category: "SpectralCard" }),
  8206: Object.freeze({ value: 8206, enumName: "Medium", displayName: "Medium", category: "SpectralCard" }),
  8207: Object.freeze({ value: 8207, enumName: "Cryptid", displayName: "Cryptid", category: "SpectralCard" }),
  8208: Object.freeze({ value: 8208, enumName: "TheSoul", displayName: "The Soul", category: "SpectralCard" }),
  8209: Object.freeze({ value: 8209, enumName: "BlackHole", displayName: "Black Hole", category: "SpectralCard" }),
  12288: Object.freeze({ value: 12288, enumName: "TheFool", displayName: "The Fool", category: "TarotCard" }),
  12289: Object.freeze({ value: 12289, enumName: "TheMagician", displayName: "The Magician", category: "TarotCard" }),
  12290: Object.freeze({ value: 12290, enumName: "TheHighPriestess", displayName: "The High Priestess", category: "TarotCard" }),
  12291: Object.freeze({ value: 12291, enumName: "TheEmpress", displayName: "The Empress", category: "TarotCard" }),
  12292: Object.freeze({ value: 12292, enumName: "TheEmperor", displayName: "The Emperor", category: "TarotCard" }),
  12293: Object.freeze({ value: 12293, enumName: "TheHierophant", displayName: "The Hierophant", category: "TarotCard" }),
  12294: Object.freeze({ value: 12294, enumName: "TheLovers", displayName: "The Lovers", category: "TarotCard" }),
  12295: Object.freeze({ value: 12295, enumName: "TheChariot", displayName: "The Chariot", category: "TarotCard" }),
  12296: Object.freeze({ value: 12296, enumName: "Justice", displayName: "Justice", category: "TarotCard" }),
  12297: Object.freeze({ value: 12297, enumName: "TheHermit", displayName: "The Hermit", category: "TarotCard" }),
  12298: Object.freeze({ value: 12298, enumName: "TheWheelOfFortune", displayName: "The Wheel of Fortune", category: "TarotCard" }),
  12299: Object.freeze({ value: 12299, enumName: "Strength", displayName: "Strength", category: "TarotCard" }),
  12300: Object.freeze({ value: 12300, enumName: "TheHangedMan", displayName: "The Hanged Man", category: "TarotCard" }),
  12301: Object.freeze({ value: 12301, enumName: "Death", displayName: "Death", category: "TarotCard" }),
  12302: Object.freeze({ value: 12302, enumName: "Temperance", displayName: "Temperance", category: "TarotCard" }),
  12303: Object.freeze({ value: 12303, enumName: "TheDevil", displayName: "The Devil", category: "TarotCard" }),
  12304: Object.freeze({ value: 12304, enumName: "TheTower", displayName: "The Tower", category: "TarotCard" }),
  12305: Object.freeze({ value: 12305, enumName: "TheStar", displayName: "The Star", category: "TarotCard" }),
  12306: Object.freeze({ value: 12306, enumName: "TheMoon", displayName: "The Moon", category: "TarotCard" }),
  12307: Object.freeze({ value: 12307, enumName: "TheSun", displayName: "The Sun", category: "TarotCard" }),
  12308: Object.freeze({ value: 12308, enumName: "Judgement", displayName: "Judgement", category: "TarotCard" }),
  12309: Object.freeze({ value: 12309, enumName: "TheWorld", displayName: "The World", category: "TarotCard" }),
  16384: Object.freeze({ value: 16384, enumName: "Mercury", displayName: "Mercury", category: "PlanetCard" }),
  16385: Object.freeze({ value: 16385, enumName: "Venus", displayName: "Venus", category: "PlanetCard" }),
  16386: Object.freeze({ value: 16386, enumName: "Earth", displayName: "Earth", category: "PlanetCard" }),
  16387: Object.freeze({ value: 16387, enumName: "Mars", displayName: "Mars", category: "PlanetCard" }),
  16388: Object.freeze({ value: 16388, enumName: "Jupiter", displayName: "Jupiter", category: "PlanetCard" }),
  16389: Object.freeze({ value: 16389, enumName: "Saturn", displayName: "Saturn", category: "PlanetCard" }),
  16390: Object.freeze({ value: 16390, enumName: "Uranus", displayName: "Uranus", category: "PlanetCard" }),
  16391: Object.freeze({ value: 16391, enumName: "Neptune", displayName: "Neptune", category: "PlanetCard" }),
  16392: Object.freeze({ value: 16392, enumName: "Pluto", displayName: "Pluto", category: "PlanetCard" }),
  16393: Object.freeze({ value: 16393, enumName: "PlanetX", displayName: "Planet X", category: "PlanetCard" }),
  16394: Object.freeze({ value: 16394, enumName: "Ceres", displayName: "Ceres", category: "PlanetCard" }),
  16395: Object.freeze({ value: 16395, enumName: "Eris", displayName: "Eris", category: "PlanetCard" }),
  20480: Object.freeze({ value: 20480, enumName: "Joker", displayName: "Joker", category: "Joker" }),
  20481: Object.freeze({ value: 20481, enumName: "GreedyJoker", displayName: "Greedy Joker", category: "Joker" }),
  20482: Object.freeze({ value: 20482, enumName: "LustyJoker", displayName: "Lusty Joker", category: "Joker" }),
  20483: Object.freeze({ value: 20483, enumName: "WrathfulJoker", displayName: "Wrathful Joker", category: "Joker" }),
  20484: Object.freeze({ value: 20484, enumName: "GluttonousJoker", displayName: "Gluttonous Joker", category: "Joker" }),
  20485: Object.freeze({ value: 20485, enumName: "JollyJoker", displayName: "Jolly Joker", category: "Joker" }),
  20486: Object.freeze({ value: 20486, enumName: "ZanyJoker", displayName: "Zany Joker", category: "Joker" }),
  20487: Object.freeze({ value: 20487, enumName: "MadJoker", displayName: "Mad Joker", category: "Joker" }),
  20488: Object.freeze({ value: 20488, enumName: "CrazyJoker", displayName: "Crazy Joker", category: "Joker" }),
  20489: Object.freeze({ value: 20489, enumName: "DrollJoker", displayName: "Droll Joker", category: "Joker" }),
  20490: Object.freeze({ value: 20490, enumName: "SlyJoker", displayName: "Sly Joker", category: "Joker" }),
  20491: Object.freeze({ value: 20491, enumName: "WilyJoker", displayName: "Wily Joker", category: "Joker" }),
  20492: Object.freeze({ value: 20492, enumName: "CleverJoker", displayName: "Clever Joker", category: "Joker" }),
  20493: Object.freeze({ value: 20493, enumName: "DeviousJoker", displayName: "Devious Joker", category: "Joker" }),
  20494: Object.freeze({ value: 20494, enumName: "CraftyJoker", displayName: "Crafty Joker", category: "Joker" }),
  20495: Object.freeze({ value: 20495, enumName: "HalfJoker", displayName: "Half Joker", category: "Joker" }),
  20496: Object.freeze({ value: 20496, enumName: "CreditCard", displayName: "Credit Card", category: "Joker" }),
  20497: Object.freeze({ value: 20497, enumName: "Banner", displayName: "Banner", category: "Joker" }),
  20498: Object.freeze({ value: 20498, enumName: "MysticSummit", displayName: "Mystic Summit", category: "Joker" }),
  20499: Object.freeze({ value: 20499, enumName: "EightBall", displayName: "8 Ball", category: "Joker" }),
  20500: Object.freeze({ value: 20500, enumName: "Misprint", displayName: "Misprint", category: "Joker" }),
  20501: Object.freeze({ value: 20501, enumName: "RaisedFist", displayName: "Raised Fist", category: "Joker" }),
  20502: Object.freeze({ value: 20502, enumName: "ChaostheClown", displayName: "Chaos the Clown", category: "Joker" }),
  20503: Object.freeze({ value: 20503, enumName: "ScaryFace", displayName: "Scary Face", category: "Joker" }),
  20504: Object.freeze({ value: 20504, enumName: "AbstractJoker", displayName: "Abstract Joker", category: "Joker" }),
  20505: Object.freeze({ value: 20505, enumName: "DelayedGratification", displayName: "Delayed Gratification", category: "Joker" }),
  20506: Object.freeze({ value: 20506, enumName: "GrosMichel", displayName: "Gros Michel", category: "Joker" }),
  20507: Object.freeze({ value: 20507, enumName: "EvenSteven", displayName: "Even Steven", category: "Joker" }),
  20508: Object.freeze({ value: 20508, enumName: "OddTodd", displayName: "Odd Todd", category: "Joker" }),
  20509: Object.freeze({ value: 20509, enumName: "Scholar", displayName: "Scholar", category: "Joker" }),
  20510: Object.freeze({ value: 20510, enumName: "BusinessCard", displayName: "Business Card", category: "Joker" }),
  20511: Object.freeze({ value: 20511, enumName: "Supernova", displayName: "Supernova", category: "Joker" }),
  20512: Object.freeze({ value: 20512, enumName: "RideTheBus", displayName: "Ride the Bus", category: "Joker" }),
  20513: Object.freeze({ value: 20513, enumName: "Egg", displayName: "Egg", category: "Joker" }),
  20514: Object.freeze({ value: 20514, enumName: "Runner", displayName: "Runner", category: "Joker" }),
  20515: Object.freeze({ value: 20515, enumName: "IceCream", displayName: "Ice Cream", category: "Joker" }),
  20516: Object.freeze({ value: 20516, enumName: "Splash", displayName: "Splash", category: "Joker" }),
  20517: Object.freeze({ value: 20517, enumName: "BlueJoker", displayName: "Blue Joker", category: "Joker" }),
  20518: Object.freeze({ value: 20518, enumName: "FacelessJoker", displayName: "Faceless Joker", category: "Joker" }),
  20519: Object.freeze({ value: 20519, enumName: "GreenJoker", displayName: "Green Joker", category: "Joker" }),
  20520: Object.freeze({ value: 20520, enumName: "Superposition", displayName: "Superposition", category: "Joker" }),
  20521: Object.freeze({ value: 20521, enumName: "ToDoList", displayName: "To Do List", category: "Joker" }),
  20522: Object.freeze({ value: 20522, enumName: "Cavendish", displayName: "Cavendish", category: "Joker" }),
  20523: Object.freeze({ value: 20523, enumName: "RedCard", displayName: "Red Card", category: "Joker" }),
  20524: Object.freeze({ value: 20524, enumName: "SquareJoker", displayName: "Square Joker", category: "Joker" }),
  20525: Object.freeze({ value: 20525, enumName: "RiffRaff", displayName: "Riff-raff", category: "Joker" }),
  20526: Object.freeze({ value: 20526, enumName: "Photograph", displayName: "Photograph", category: "Joker" }),
  20527: Object.freeze({ value: 20527, enumName: "ReservedParking", displayName: "Reserved Parking", category: "Joker" }),
  20528: Object.freeze({ value: 20528, enumName: "MailInRebate", displayName: "Mail In Rebate", category: "Joker" }),
  20529: Object.freeze({ value: 20529, enumName: "Hallucination", displayName: "Hallucination", category: "Joker" }),
  20530: Object.freeze({ value: 20530, enumName: "FortuneTeller", displayName: "Fortune Teller", category: "Joker" }),
  20531: Object.freeze({ value: 20531, enumName: "Juggler", displayName: "Juggler", category: "Joker" }),
  20532: Object.freeze({ value: 20532, enumName: "Drunkard", displayName: "Drunkard", category: "Joker" }),
  20533: Object.freeze({ value: 20533, enumName: "GoldenJoker", displayName: "Golden Joker", category: "Joker" }),
  20534: Object.freeze({ value: 20534, enumName: "Popcorn", displayName: "Popcorn", category: "Joker" }),
  20535: Object.freeze({ value: 20535, enumName: "WalkieTalkie", displayName: "Walkie Talkie", category: "Joker" }),
  20536: Object.freeze({ value: 20536, enumName: "SmileyFace", displayName: "Smiley Face", category: "Joker" }),
  20537: Object.freeze({ value: 20537, enumName: "GoldenTicket", displayName: "Golden Ticket", category: "Joker" }),
  20538: Object.freeze({ value: 20538, enumName: "Swashbuckler", displayName: "Swashbuckler", category: "Joker" }),
  20539: Object.freeze({ value: 20539, enumName: "HangingChad", displayName: "Hanging Chad", category: "Joker" }),
  20540: Object.freeze({ value: 20540, enumName: "ShootTheMoon", displayName: "Shoot the Moon", category: "Joker" }),
  21504: Object.freeze({ value: 21504, enumName: "JokerStencil", displayName: "Joker Stencil", category: "Joker" }),
  21505: Object.freeze({ value: 21505, enumName: "FourFingers", displayName: "Four Fingers", category: "Joker" }),
  21506: Object.freeze({ value: 21506, enumName: "Mime", displayName: "Mime", category: "Joker" }),
  21507: Object.freeze({ value: 21507, enumName: "CeremonialDagger", displayName: "Ceremonial Dagger", category: "Joker" }),
  21508: Object.freeze({ value: 21508, enumName: "MarbleJoker", displayName: "Marble Joker", category: "Joker" }),
  21509: Object.freeze({ value: 21509, enumName: "LoyaltyCard", displayName: "Loyalty Card", category: "Joker" }),
  21510: Object.freeze({ value: 21510, enumName: "Dusk", displayName: "Dusk", category: "Joker" }),
  21511: Object.freeze({ value: 21511, enumName: "Fibonacci", displayName: "Fibonacci", category: "Joker" }),
  21512: Object.freeze({ value: 21512, enumName: "SteelJoker", displayName: "Steel Joker", category: "Joker" }),
  21513: Object.freeze({ value: 21513, enumName: "Hack", displayName: "Hack", category: "Joker" }),
  21514: Object.freeze({ value: 21514, enumName: "Pareidolia", displayName: "Pareidolia", category: "Joker" }),
  21515: Object.freeze({ value: 21515, enumName: "SpaceJoker", displayName: "Space Joker", category: "Joker" }),
  21516: Object.freeze({ value: 21516, enumName: "Burglar", displayName: "Burglar", category: "Joker" }),
  21517: Object.freeze({ value: 21517, enumName: "Blackboard", displayName: "Blackboard", category: "Joker" }),
  21518: Object.freeze({ value: 21518, enumName: "SixthSense", displayName: "Sixth Sense", category: "Joker" }),
  21519: Object.freeze({ value: 21519, enumName: "Constellation", displayName: "Constellation", category: "Joker" }),
  21520: Object.freeze({ value: 21520, enumName: "Hiker", displayName: "Hiker", category: "Joker" }),
  21521: Object.freeze({ value: 21521, enumName: "CardSharp", displayName: "Card Sharp", category: "Joker" }),
  21522: Object.freeze({ value: 21522, enumName: "Madness", displayName: "Madness", category: "Joker" }),
  21523: Object.freeze({ value: 21523, enumName: "Seance", displayName: "Seance", category: "Joker" }),
  21524: Object.freeze({ value: 21524, enumName: "Vampire", displayName: "Vampire", category: "Joker" }),
  21525: Object.freeze({ value: 21525, enumName: "Shortcut", displayName: "Shortcut", category: "Joker" }),
  21526: Object.freeze({ value: 21526, enumName: "Hologram", displayName: "Hologram", category: "Joker" }),
  21527: Object.freeze({ value: 21527, enumName: "Cloud9", displayName: "Cloud 9", category: "Joker" }),
  21528: Object.freeze({ value: 21528, enumName: "Rocket", displayName: "Rocket", category: "Joker" }),
  21529: Object.freeze({ value: 21529, enumName: "MidasMask", displayName: "Midas Mask", category: "Joker" }),
  21530: Object.freeze({ value: 21530, enumName: "Luchador", displayName: "Luchador", category: "Joker" }),
  21531: Object.freeze({ value: 21531, enumName: "GiftCard", displayName: "Gift Card", category: "Joker" }),
  21532: Object.freeze({ value: 21532, enumName: "TurtleBean", displayName: "Turtle Bean", category: "Joker" }),
  21533: Object.freeze({ value: 21533, enumName: "Erosion", displayName: "Erosion", category: "Joker" }),
  21534: Object.freeze({ value: 21534, enumName: "ToTheMoon", displayName: "To the Moon", category: "Joker" }),
  21535: Object.freeze({ value: 21535, enumName: "StoneJoker", displayName: "Stone Joker", category: "Joker" }),
  21536: Object.freeze({ value: 21536, enumName: "LuckyCat", displayName: "Lucky Cat", category: "Joker" }),
  21537: Object.freeze({ value: 21537, enumName: "Bull", displayName: "Bull", category: "Joker" }),
  21538: Object.freeze({ value: 21538, enumName: "DietCola", displayName: "Diet Cola", category: "Joker" }),
  21539: Object.freeze({ value: 21539, enumName: "TradingCard", displayName: "Trading Card", category: "Joker" }),
  21540: Object.freeze({ value: 21540, enumName: "FlashCard", displayName: "Flash Card", category: "Joker" }),
  21541: Object.freeze({ value: 21541, enumName: "SpareTrousers", displayName: "Spare Trousers", category: "Joker" }),
  21542: Object.freeze({ value: 21542, enumName: "Ramen", displayName: "Ramen", category: "Joker" }),
  21543: Object.freeze({ value: 21543, enumName: "Seltzer", displayName: "Seltzer", category: "Joker" }),
  21544: Object.freeze({ value: 21544, enumName: "Castle", displayName: "Castle", category: "Joker" }),
  21545: Object.freeze({ value: 21545, enumName: "MrBones", displayName: "Mr. Bones", category: "Joker" }),
  21546: Object.freeze({ value: 21546, enumName: "Acrobat", displayName: "Acrobat", category: "Joker" }),
  21547: Object.freeze({ value: 21547, enumName: "SockAndBuskin", displayName: "Sock and Buskin", category: "Joker" }),
  21548: Object.freeze({ value: 21548, enumName: "Troubadour", displayName: "Troubadour", category: "Joker" }),
  21549: Object.freeze({ value: 21549, enumName: "Certificate", displayName: "Certificate", category: "Joker" }),
  21550: Object.freeze({ value: 21550, enumName: "SmearedJoker", displayName: "Smeared Joker", category: "Joker" }),
  21551: Object.freeze({ value: 21551, enumName: "Throwback", displayName: "Throwback", category: "Joker" }),
  21552: Object.freeze({ value: 21552, enumName: "RoughGem", displayName: "Rough Gem", category: "Joker" }),
  21553: Object.freeze({ value: 21553, enumName: "Bloodstone", displayName: "Bloodstone", category: "Joker" }),
  21554: Object.freeze({ value: 21554, enumName: "Arrowhead", displayName: "Arrowhead", category: "Joker" }),
  21555: Object.freeze({ value: 21555, enumName: "OnyxAgate", displayName: "Onyx Agate", category: "Joker" }),
  21556: Object.freeze({ value: 21556, enumName: "GlassJoker", displayName: "Glass Joker", category: "Joker" }),
  21557: Object.freeze({ value: 21557, enumName: "Showman", displayName: "Showman", category: "Joker" }),
  21558: Object.freeze({ value: 21558, enumName: "FlowerPot", displayName: "Flower Pot", category: "Joker" }),
  21559: Object.freeze({ value: 21559, enumName: "MerryAndy", displayName: "Merry Andy", category: "Joker" }),
  21560: Object.freeze({ value: 21560, enumName: "OopsAll6s", displayName: "Oops! All 6s", category: "Joker" }),
  21561: Object.freeze({ value: 21561, enumName: "TheIdol", displayName: "The Idol", category: "Joker" }),
  21562: Object.freeze({ value: 21562, enumName: "SeeingDouble", displayName: "Seeing Double", category: "Joker" }),
  21563: Object.freeze({ value: 21563, enumName: "Matador", displayName: "Matador", category: "Joker" }),
  21564: Object.freeze({ value: 21564, enumName: "Satellite", displayName: "Satellite", category: "Joker" }),
  21565: Object.freeze({ value: 21565, enumName: "Cartomancer", displayName: "Cartomancer", category: "Joker" }),
  21566: Object.freeze({ value: 21566, enumName: "Astronomer", displayName: "Astronomer", category: "Joker" }),
  21567: Object.freeze({ value: 21567, enumName: "Bootstraps", displayName: "Bootstraps", category: "Joker" }),
  22528: Object.freeze({ value: 22528, enumName: "DNA", displayName: "DNA", category: "Joker" }),
  22529: Object.freeze({ value: 22529, enumName: "Vagabond", displayName: "Vagabond", category: "Joker" }),
  22530: Object.freeze({ value: 22530, enumName: "Baron", displayName: "Baron", category: "Joker" }),
  22531: Object.freeze({ value: 22531, enumName: "Obelisk", displayName: "Obelisk", category: "Joker" }),
  22532: Object.freeze({ value: 22532, enumName: "BaseballCard", displayName: "Baseball Card", category: "Joker" }),
  22533: Object.freeze({ value: 22533, enumName: "AncientJoker", displayName: "Ancient Joker", category: "Joker" }),
  22534: Object.freeze({ value: 22534, enumName: "Campfire", displayName: "Campfire", category: "Joker" }),
  22535: Object.freeze({ value: 22535, enumName: "Blueprint", displayName: "Blueprint", category: "Joker" }),
  22536: Object.freeze({ value: 22536, enumName: "WeeJoker", displayName: "Wee Joker", category: "Joker" }),
  22537: Object.freeze({ value: 22537, enumName: "HitTheRoad", displayName: "Hit the Road", category: "Joker" }),
  22538: Object.freeze({ value: 22538, enumName: "TheDuo", displayName: "The Duo", category: "Joker" }),
  22539: Object.freeze({ value: 22539, enumName: "TheTrio", displayName: "The Trio", category: "Joker" }),
  22540: Object.freeze({ value: 22540, enumName: "TheFamily", displayName: "The Family", category: "Joker" }),
  22541: Object.freeze({ value: 22541, enumName: "TheOrder", displayName: "The Order", category: "Joker" }),
  22542: Object.freeze({ value: 22542, enumName: "TheTribe", displayName: "The Tribe", category: "Joker" }),
  22543: Object.freeze({ value: 22543, enumName: "Stuntman", displayName: "Stuntman", category: "Joker" }),
  22544: Object.freeze({ value: 22544, enumName: "InvisibleJoker", displayName: "Invisible Joker", category: "Joker" }),
  22545: Object.freeze({ value: 22545, enumName: "Brainstorm", displayName: "Brainstorm", category: "Joker" }),
  22546: Object.freeze({ value: 22546, enumName: "DriversLicense", displayName: "Driver\u0027s License", category: "Joker" }),
  22547: Object.freeze({ value: 22547, enumName: "BurntJoker", displayName: "Burnt Joker", category: "Joker" }),
  23552: Object.freeze({ value: 23552, enumName: "Canio", displayName: "Canio", category: "Joker" }),
  23553: Object.freeze({ value: 23553, enumName: "Triboulet", displayName: "Triboulet", category: "Joker" }),
  23554: Object.freeze({ value: 23554, enumName: "Yorick", displayName: "Yorick", category: "Joker" }),
  23555: Object.freeze({ value: 23555, enumName: "Chicot", displayName: "Chicot", category: "Joker" }),
  23556: Object.freeze({ value: 23556, enumName: "Perkeo", displayName: "Perkeo", category: "Joker" }),
  61440: Object.freeze({ value: 61440, enumName: "Invalid", displayName: "Invalid", category: "Invalid" }),
  61441: Object.freeze({ value: 61441, enumName: "NotImplemented", displayName: "Not Implemented", category: "Invalid" }),
  61442: Object.freeze({ value: 61442, enumName: "JokerExcludedByStream", displayName: "Joker Excluded By Stream", category: "Invalid" }),
  61443: Object.freeze({ value: 61443, enumName: "PlanetExcludedByStream", displayName: "Planet Excluded By Stream", category: "Invalid" }),
  61444: Object.freeze({ value: 61444, enumName: "TarotExcludedByStream", displayName: "Tarot Excluded By Stream", category: "Invalid" }),
  61445: Object.freeze({ value: 61445, enumName: "SpectralExcludedByStream", displayName: "Spectral Excluded By Stream", category: "Invalid" }),
});

export const MOTELY_ITEM_FORMATS_BY_ENUM_NAME = Object.freeze({
  AbstractJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20504],
  AceOfClubs: MOTELY_ITEM_FORMATS_BY_VALUE[4108],
  AceOfDiamonds: MOTELY_ITEM_FORMATS_BY_VALUE[4124],
  AceOfHearts: MOTELY_ITEM_FORMATS_BY_VALUE[4140],
  AceOfSpades: MOTELY_ITEM_FORMATS_BY_VALUE[4156],
  Acrobat: MOTELY_ITEM_FORMATS_BY_VALUE[21546],
  AncientJoker: MOTELY_ITEM_FORMATS_BY_VALUE[22533],
  Ankh: MOTELY_ITEM_FORMATS_BY_VALUE[8202],
  Arrowhead: MOTELY_ITEM_FORMATS_BY_VALUE[21554],
  Astronomer: MOTELY_ITEM_FORMATS_BY_VALUE[21566],
  Aura: MOTELY_ITEM_FORMATS_BY_VALUE[8196],
  Banner: MOTELY_ITEM_FORMATS_BY_VALUE[20497],
  Baron: MOTELY_ITEM_FORMATS_BY_VALUE[22530],
  BaseballCard: MOTELY_ITEM_FORMATS_BY_VALUE[22532],
  BlackHole: MOTELY_ITEM_FORMATS_BY_VALUE[8209],
  Blackboard: MOTELY_ITEM_FORMATS_BY_VALUE[21517],
  Bloodstone: MOTELY_ITEM_FORMATS_BY_VALUE[21553],
  BlueJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20517],
  Blueprint: MOTELY_ITEM_FORMATS_BY_VALUE[22535],
  Bootstraps: MOTELY_ITEM_FORMATS_BY_VALUE[21567],
  Brainstorm: MOTELY_ITEM_FORMATS_BY_VALUE[22545],
  Bull: MOTELY_ITEM_FORMATS_BY_VALUE[21537],
  Burglar: MOTELY_ITEM_FORMATS_BY_VALUE[21516],
  BurntJoker: MOTELY_ITEM_FORMATS_BY_VALUE[22547],
  BusinessCard: MOTELY_ITEM_FORMATS_BY_VALUE[20510],
  Campfire: MOTELY_ITEM_FORMATS_BY_VALUE[22534],
  Canio: MOTELY_ITEM_FORMATS_BY_VALUE[23552],
  CardSharp: MOTELY_ITEM_FORMATS_BY_VALUE[21521],
  Cartomancer: MOTELY_ITEM_FORMATS_BY_VALUE[21565],
  Castle: MOTELY_ITEM_FORMATS_BY_VALUE[21544],
  Cavendish: MOTELY_ITEM_FORMATS_BY_VALUE[20522],
  CeremonialDagger: MOTELY_ITEM_FORMATS_BY_VALUE[21507],
  Ceres: MOTELY_ITEM_FORMATS_BY_VALUE[16394],
  Certificate: MOTELY_ITEM_FORMATS_BY_VALUE[21549],
  ChaostheClown: MOTELY_ITEM_FORMATS_BY_VALUE[20502],
  Chicot: MOTELY_ITEM_FORMATS_BY_VALUE[23555],
  CleverJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20492],
  Cloud9: MOTELY_ITEM_FORMATS_BY_VALUE[21527],
  Constellation: MOTELY_ITEM_FORMATS_BY_VALUE[21519],
  CraftyJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20494],
  CrazyJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20488],
  CreditCard: MOTELY_ITEM_FORMATS_BY_VALUE[20496],
  Cryptid: MOTELY_ITEM_FORMATS_BY_VALUE[8207],
  DNA: MOTELY_ITEM_FORMATS_BY_VALUE[22528],
  Death: MOTELY_ITEM_FORMATS_BY_VALUE[12301],
  DejaVu: MOTELY_ITEM_FORMATS_BY_VALUE[8203],
  DelayedGratification: MOTELY_ITEM_FORMATS_BY_VALUE[20505],
  DeviousJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20493],
  DietCola: MOTELY_ITEM_FORMATS_BY_VALUE[21538],
  DriversLicense: MOTELY_ITEM_FORMATS_BY_VALUE[22546],
  DrollJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20489],
  Drunkard: MOTELY_ITEM_FORMATS_BY_VALUE[20532],
  Dusk: MOTELY_ITEM_FORMATS_BY_VALUE[21510],
  Earth: MOTELY_ITEM_FORMATS_BY_VALUE[16386],
  Ectoplasm: MOTELY_ITEM_FORMATS_BY_VALUE[8200],
  Egg: MOTELY_ITEM_FORMATS_BY_VALUE[20513],
  EightBall: MOTELY_ITEM_FORMATS_BY_VALUE[20499],
  EightOfClubs: MOTELY_ITEM_FORMATS_BY_VALUE[4102],
  EightOfDiamonds: MOTELY_ITEM_FORMATS_BY_VALUE[4118],
  EightOfHearts: MOTELY_ITEM_FORMATS_BY_VALUE[4134],
  EightOfSpades: MOTELY_ITEM_FORMATS_BY_VALUE[4150],
  Eris: MOTELY_ITEM_FORMATS_BY_VALUE[16395],
  Erosion: MOTELY_ITEM_FORMATS_BY_VALUE[21533],
  EvenSteven: MOTELY_ITEM_FORMATS_BY_VALUE[20507],
  FacelessJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20518],
  Familiar: MOTELY_ITEM_FORMATS_BY_VALUE[8192],
  Fibonacci: MOTELY_ITEM_FORMATS_BY_VALUE[21511],
  FiveOfClubs: MOTELY_ITEM_FORMATS_BY_VALUE[4099],
  FiveOfDiamonds: MOTELY_ITEM_FORMATS_BY_VALUE[4115],
  FiveOfHearts: MOTELY_ITEM_FORMATS_BY_VALUE[4131],
  FiveOfSpades: MOTELY_ITEM_FORMATS_BY_VALUE[4147],
  FlashCard: MOTELY_ITEM_FORMATS_BY_VALUE[21540],
  FlowerPot: MOTELY_ITEM_FORMATS_BY_VALUE[21558],
  FortuneTeller: MOTELY_ITEM_FORMATS_BY_VALUE[20530],
  FourFingers: MOTELY_ITEM_FORMATS_BY_VALUE[21505],
  FourOfClubs: MOTELY_ITEM_FORMATS_BY_VALUE[4098],
  FourOfDiamonds: MOTELY_ITEM_FORMATS_BY_VALUE[4114],
  FourOfHearts: MOTELY_ITEM_FORMATS_BY_VALUE[4130],
  FourOfSpades: MOTELY_ITEM_FORMATS_BY_VALUE[4146],
  GiftCard: MOTELY_ITEM_FORMATS_BY_VALUE[21531],
  GlassJoker: MOTELY_ITEM_FORMATS_BY_VALUE[21556],
  GluttonousJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20484],
  GoldenJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20533],
  GoldenTicket: MOTELY_ITEM_FORMATS_BY_VALUE[20537],
  GreedyJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20481],
  GreenJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20519],
  Grim: MOTELY_ITEM_FORMATS_BY_VALUE[8193],
  GrosMichel: MOTELY_ITEM_FORMATS_BY_VALUE[20506],
  Hack: MOTELY_ITEM_FORMATS_BY_VALUE[21513],
  HalfJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20495],
  Hallucination: MOTELY_ITEM_FORMATS_BY_VALUE[20529],
  HangingChad: MOTELY_ITEM_FORMATS_BY_VALUE[20539],
  Hex: MOTELY_ITEM_FORMATS_BY_VALUE[8204],
  Hiker: MOTELY_ITEM_FORMATS_BY_VALUE[21520],
  HitTheRoad: MOTELY_ITEM_FORMATS_BY_VALUE[22537],
  Hologram: MOTELY_ITEM_FORMATS_BY_VALUE[21526],
  IceCream: MOTELY_ITEM_FORMATS_BY_VALUE[20515],
  Immolate: MOTELY_ITEM_FORMATS_BY_VALUE[8201],
  Incantation: MOTELY_ITEM_FORMATS_BY_VALUE[8194],
  Invalid: MOTELY_ITEM_FORMATS_BY_VALUE[61440],
  InvisibleJoker: MOTELY_ITEM_FORMATS_BY_VALUE[22544],
  JackOfClubs: MOTELY_ITEM_FORMATS_BY_VALUE[4105],
  JackOfDiamonds: MOTELY_ITEM_FORMATS_BY_VALUE[4121],
  JackOfHearts: MOTELY_ITEM_FORMATS_BY_VALUE[4137],
  JackOfSpades: MOTELY_ITEM_FORMATS_BY_VALUE[4153],
  Joker: MOTELY_ITEM_FORMATS_BY_VALUE[20480],
  JokerExcludedByStream: MOTELY_ITEM_FORMATS_BY_VALUE[61442],
  JokerStencil: MOTELY_ITEM_FORMATS_BY_VALUE[21504],
  JollyJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20485],
  Judgement: MOTELY_ITEM_FORMATS_BY_VALUE[12308],
  Juggler: MOTELY_ITEM_FORMATS_BY_VALUE[20531],
  Jupiter: MOTELY_ITEM_FORMATS_BY_VALUE[16388],
  Justice: MOTELY_ITEM_FORMATS_BY_VALUE[12296],
  KingOfClubs: MOTELY_ITEM_FORMATS_BY_VALUE[4107],
  KingOfDiamonds: MOTELY_ITEM_FORMATS_BY_VALUE[4123],
  KingOfHearts: MOTELY_ITEM_FORMATS_BY_VALUE[4139],
  KingOfSpades: MOTELY_ITEM_FORMATS_BY_VALUE[4155],
  LoyaltyCard: MOTELY_ITEM_FORMATS_BY_VALUE[21509],
  Luchador: MOTELY_ITEM_FORMATS_BY_VALUE[21530],
  LuckyCat: MOTELY_ITEM_FORMATS_BY_VALUE[21536],
  LustyJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20482],
  MadJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20487],
  Madness: MOTELY_ITEM_FORMATS_BY_VALUE[21522],
  MailInRebate: MOTELY_ITEM_FORMATS_BY_VALUE[20528],
  MarbleJoker: MOTELY_ITEM_FORMATS_BY_VALUE[21508],
  Mars: MOTELY_ITEM_FORMATS_BY_VALUE[16387],
  Matador: MOTELY_ITEM_FORMATS_BY_VALUE[21563],
  Medium: MOTELY_ITEM_FORMATS_BY_VALUE[8206],
  Mercury: MOTELY_ITEM_FORMATS_BY_VALUE[16384],
  MerryAndy: MOTELY_ITEM_FORMATS_BY_VALUE[21559],
  MidasMask: MOTELY_ITEM_FORMATS_BY_VALUE[21529],
  Mime: MOTELY_ITEM_FORMATS_BY_VALUE[21506],
  Misprint: MOTELY_ITEM_FORMATS_BY_VALUE[20500],
  MrBones: MOTELY_ITEM_FORMATS_BY_VALUE[21545],
  MysticSummit: MOTELY_ITEM_FORMATS_BY_VALUE[20498],
  Neptune: MOTELY_ITEM_FORMATS_BY_VALUE[16391],
  NineOfClubs: MOTELY_ITEM_FORMATS_BY_VALUE[4103],
  NineOfDiamonds: MOTELY_ITEM_FORMATS_BY_VALUE[4119],
  NineOfHearts: MOTELY_ITEM_FORMATS_BY_VALUE[4135],
  NineOfSpades: MOTELY_ITEM_FORMATS_BY_VALUE[4151],
  NotImplemented: MOTELY_ITEM_FORMATS_BY_VALUE[61441],
  Obelisk: MOTELY_ITEM_FORMATS_BY_VALUE[22531],
  OddTodd: MOTELY_ITEM_FORMATS_BY_VALUE[20508],
  OnyxAgate: MOTELY_ITEM_FORMATS_BY_VALUE[21555],
  OopsAll6s: MOTELY_ITEM_FORMATS_BY_VALUE[21560],
  Ouija: MOTELY_ITEM_FORMATS_BY_VALUE[8199],
  Pareidolia: MOTELY_ITEM_FORMATS_BY_VALUE[21514],
  Perkeo: MOTELY_ITEM_FORMATS_BY_VALUE[23556],
  Photograph: MOTELY_ITEM_FORMATS_BY_VALUE[20526],
  PlanetExcludedByStream: MOTELY_ITEM_FORMATS_BY_VALUE[61443],
  PlanetX: MOTELY_ITEM_FORMATS_BY_VALUE[16393],
  Pluto: MOTELY_ITEM_FORMATS_BY_VALUE[16392],
  Popcorn: MOTELY_ITEM_FORMATS_BY_VALUE[20534],
  QueenOfClubs: MOTELY_ITEM_FORMATS_BY_VALUE[4106],
  QueenOfDiamonds: MOTELY_ITEM_FORMATS_BY_VALUE[4122],
  QueenOfHearts: MOTELY_ITEM_FORMATS_BY_VALUE[4138],
  QueenOfSpades: MOTELY_ITEM_FORMATS_BY_VALUE[4154],
  RaisedFist: MOTELY_ITEM_FORMATS_BY_VALUE[20501],
  Ramen: MOTELY_ITEM_FORMATS_BY_VALUE[21542],
  RedCard: MOTELY_ITEM_FORMATS_BY_VALUE[20523],
  ReservedParking: MOTELY_ITEM_FORMATS_BY_VALUE[20527],
  RideTheBus: MOTELY_ITEM_FORMATS_BY_VALUE[20512],
  RiffRaff: MOTELY_ITEM_FORMATS_BY_VALUE[20525],
  Rocket: MOTELY_ITEM_FORMATS_BY_VALUE[21528],
  RoughGem: MOTELY_ITEM_FORMATS_BY_VALUE[21552],
  Runner: MOTELY_ITEM_FORMATS_BY_VALUE[20514],
  Satellite: MOTELY_ITEM_FORMATS_BY_VALUE[21564],
  Saturn: MOTELY_ITEM_FORMATS_BY_VALUE[16389],
  ScaryFace: MOTELY_ITEM_FORMATS_BY_VALUE[20503],
  Scholar: MOTELY_ITEM_FORMATS_BY_VALUE[20509],
  Seance: MOTELY_ITEM_FORMATS_BY_VALUE[21523],
  SeeingDouble: MOTELY_ITEM_FORMATS_BY_VALUE[21562],
  Seltzer: MOTELY_ITEM_FORMATS_BY_VALUE[21543],
  SevenOfClubs: MOTELY_ITEM_FORMATS_BY_VALUE[4101],
  SevenOfDiamonds: MOTELY_ITEM_FORMATS_BY_VALUE[4117],
  SevenOfHearts: MOTELY_ITEM_FORMATS_BY_VALUE[4133],
  SevenOfSpades: MOTELY_ITEM_FORMATS_BY_VALUE[4149],
  ShootTheMoon: MOTELY_ITEM_FORMATS_BY_VALUE[20540],
  Shortcut: MOTELY_ITEM_FORMATS_BY_VALUE[21525],
  Showman: MOTELY_ITEM_FORMATS_BY_VALUE[21557],
  Sigil: MOTELY_ITEM_FORMATS_BY_VALUE[8198],
  SixOfClubs: MOTELY_ITEM_FORMATS_BY_VALUE[4100],
  SixOfDiamonds: MOTELY_ITEM_FORMATS_BY_VALUE[4116],
  SixOfHearts: MOTELY_ITEM_FORMATS_BY_VALUE[4132],
  SixOfSpades: MOTELY_ITEM_FORMATS_BY_VALUE[4148],
  SixthSense: MOTELY_ITEM_FORMATS_BY_VALUE[21518],
  SlyJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20490],
  SmearedJoker: MOTELY_ITEM_FORMATS_BY_VALUE[21550],
  SmileyFace: MOTELY_ITEM_FORMATS_BY_VALUE[20536],
  SockAndBuskin: MOTELY_ITEM_FORMATS_BY_VALUE[21547],
  SpaceJoker: MOTELY_ITEM_FORMATS_BY_VALUE[21515],
  SpareTrousers: MOTELY_ITEM_FORMATS_BY_VALUE[21541],
  SpectralExcludedByStream: MOTELY_ITEM_FORMATS_BY_VALUE[61445],
  Splash: MOTELY_ITEM_FORMATS_BY_VALUE[20516],
  SquareJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20524],
  SteelJoker: MOTELY_ITEM_FORMATS_BY_VALUE[21512],
  StoneJoker: MOTELY_ITEM_FORMATS_BY_VALUE[21535],
  Strength: MOTELY_ITEM_FORMATS_BY_VALUE[12299],
  Stuntman: MOTELY_ITEM_FORMATS_BY_VALUE[22543],
  Supernova: MOTELY_ITEM_FORMATS_BY_VALUE[20511],
  Superposition: MOTELY_ITEM_FORMATS_BY_VALUE[20520],
  Swashbuckler: MOTELY_ITEM_FORMATS_BY_VALUE[20538],
  Talisman: MOTELY_ITEM_FORMATS_BY_VALUE[8195],
  TarotExcludedByStream: MOTELY_ITEM_FORMATS_BY_VALUE[61444],
  Temperance: MOTELY_ITEM_FORMATS_BY_VALUE[12302],
  TenOfClubs: MOTELY_ITEM_FORMATS_BY_VALUE[4104],
  TenOfDiamonds: MOTELY_ITEM_FORMATS_BY_VALUE[4120],
  TenOfHearts: MOTELY_ITEM_FORMATS_BY_VALUE[4136],
  TenOfSpades: MOTELY_ITEM_FORMATS_BY_VALUE[4152],
  TheChariot: MOTELY_ITEM_FORMATS_BY_VALUE[12295],
  TheDevil: MOTELY_ITEM_FORMATS_BY_VALUE[12303],
  TheDuo: MOTELY_ITEM_FORMATS_BY_VALUE[22538],
  TheEmperor: MOTELY_ITEM_FORMATS_BY_VALUE[12292],
  TheEmpress: MOTELY_ITEM_FORMATS_BY_VALUE[12291],
  TheFamily: MOTELY_ITEM_FORMATS_BY_VALUE[22540],
  TheFool: MOTELY_ITEM_FORMATS_BY_VALUE[12288],
  TheHangedMan: MOTELY_ITEM_FORMATS_BY_VALUE[12300],
  TheHermit: MOTELY_ITEM_FORMATS_BY_VALUE[12297],
  TheHierophant: MOTELY_ITEM_FORMATS_BY_VALUE[12293],
  TheHighPriestess: MOTELY_ITEM_FORMATS_BY_VALUE[12290],
  TheIdol: MOTELY_ITEM_FORMATS_BY_VALUE[21561],
  TheLovers: MOTELY_ITEM_FORMATS_BY_VALUE[12294],
  TheMagician: MOTELY_ITEM_FORMATS_BY_VALUE[12289],
  TheMoon: MOTELY_ITEM_FORMATS_BY_VALUE[12306],
  TheOrder: MOTELY_ITEM_FORMATS_BY_VALUE[22541],
  TheSoul: MOTELY_ITEM_FORMATS_BY_VALUE[8208],
  TheStar: MOTELY_ITEM_FORMATS_BY_VALUE[12305],
  TheSun: MOTELY_ITEM_FORMATS_BY_VALUE[12307],
  TheTower: MOTELY_ITEM_FORMATS_BY_VALUE[12304],
  TheTribe: MOTELY_ITEM_FORMATS_BY_VALUE[22542],
  TheTrio: MOTELY_ITEM_FORMATS_BY_VALUE[22539],
  TheWheelOfFortune: MOTELY_ITEM_FORMATS_BY_VALUE[12298],
  TheWorld: MOTELY_ITEM_FORMATS_BY_VALUE[12309],
  ThreeOfClubs: MOTELY_ITEM_FORMATS_BY_VALUE[4097],
  ThreeOfDiamonds: MOTELY_ITEM_FORMATS_BY_VALUE[4113],
  ThreeOfHearts: MOTELY_ITEM_FORMATS_BY_VALUE[4129],
  ThreeOfSpades: MOTELY_ITEM_FORMATS_BY_VALUE[4145],
  Throwback: MOTELY_ITEM_FORMATS_BY_VALUE[21551],
  ToDoList: MOTELY_ITEM_FORMATS_BY_VALUE[20521],
  ToTheMoon: MOTELY_ITEM_FORMATS_BY_VALUE[21534],
  TradingCard: MOTELY_ITEM_FORMATS_BY_VALUE[21539],
  Trance: MOTELY_ITEM_FORMATS_BY_VALUE[8205],
  Triboulet: MOTELY_ITEM_FORMATS_BY_VALUE[23553],
  Troubadour: MOTELY_ITEM_FORMATS_BY_VALUE[21548],
  TurtleBean: MOTELY_ITEM_FORMATS_BY_VALUE[21532],
  TwoOfClubs: MOTELY_ITEM_FORMATS_BY_VALUE[4096],
  TwoOfDiamonds: MOTELY_ITEM_FORMATS_BY_VALUE[4112],
  TwoOfHearts: MOTELY_ITEM_FORMATS_BY_VALUE[4128],
  TwoOfSpades: MOTELY_ITEM_FORMATS_BY_VALUE[4144],
  Uranus: MOTELY_ITEM_FORMATS_BY_VALUE[16390],
  Vagabond: MOTELY_ITEM_FORMATS_BY_VALUE[22529],
  Vampire: MOTELY_ITEM_FORMATS_BY_VALUE[21524],
  Venus: MOTELY_ITEM_FORMATS_BY_VALUE[16385],
  WalkieTalkie: MOTELY_ITEM_FORMATS_BY_VALUE[20535],
  WeeJoker: MOTELY_ITEM_FORMATS_BY_VALUE[22536],
  WilyJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20491],
  Wraith: MOTELY_ITEM_FORMATS_BY_VALUE[8197],
  WrathfulJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20483],
  Yorick: MOTELY_ITEM_FORMATS_BY_VALUE[23554],
  ZanyJoker: MOTELY_ITEM_FORMATS_BY_VALUE[20486],
});
