// GENERATED by scripts/gen-engine-grammar.mjs from MotelyJAML/Motely (Filters/JamlConfigLoader.cs
// JamlClauseConverter.Keys + clause class properties). Do not edit; regenerate.
// scripts/check-vocab-drift.mjs runs every key here through the engine's JamlConfigLoader.check.

/** Top-level document keys (JamlConfig properties). */
export const ROOT_KEYS: readonly string[] = ["id","name","description","author","deck","stake","seeds","must","should","mustNot"];

/** Clause key (the YAML mapping key, e.g. `legendaryJoker`) -> the clause class it loads. */
export const DISCRIMINATORS = {
  "joker": {
    "clause": "JokerClause",
    "valueProperty": "jokers",
    "valueIsList": true
  },
  "jokers": {
    "clause": "JokerClause",
    "valueProperty": "jokers",
    "valueIsList": true
  },
  "commonJoker": {
    "clause": "CommonJokerClause",
    "valueProperty": "jokers",
    "valueIsList": true
  },
  "commonJokers": {
    "clause": "CommonJokerClause",
    "valueProperty": "jokers",
    "valueIsList": true
  },
  "uncommonJoker": {
    "clause": "UncommonJokerClause",
    "valueProperty": "jokers",
    "valueIsList": true
  },
  "uncommonJokers": {
    "clause": "UncommonJokerClause",
    "valueProperty": "jokers",
    "valueIsList": true
  },
  "rareJoker": {
    "clause": "RareJokerClause",
    "valueProperty": "jokers",
    "valueIsList": true
  },
  "rareJokers": {
    "clause": "RareJokerClause",
    "valueProperty": "jokers",
    "valueIsList": true
  },
  "legendaryJoker": {
    "clause": "LegendaryJokerClause",
    "valueProperty": "jokers",
    "valueIsList": true
  },
  "legendaryJokers": {
    "clause": "LegendaryJokerClause",
    "valueProperty": "jokers",
    "valueIsList": true
  },
  "planetCard": {
    "clause": "PlanetCardClause",
    "valueProperty": "planets",
    "valueIsList": true
  },
  "planetCards": {
    "clause": "PlanetCardClause",
    "valueProperty": "planets",
    "valueIsList": true
  },
  "spectralCard": {
    "clause": "SpectralCardClause",
    "valueProperty": "spectrals",
    "valueIsList": true
  },
  "spectralCards": {
    "clause": "SpectralCardClause",
    "valueProperty": "spectrals",
    "valueIsList": true
  },
  "tarotCard": {
    "clause": "TarotCardClause",
    "valueProperty": "tarots",
    "valueIsList": true
  },
  "tarotCards": {
    "clause": "TarotCardClause",
    "valueProperty": "tarots",
    "valueIsList": true
  },
  "standardCard": {
    "clause": "StandardCardClause",
    "valueProperty": "label",
    "valueIsList": false
  },
  "standardCards": {
    "clause": "StandardCardClause",
    "valueProperty": "label",
    "valueIsList": false
  },
  "erraticRank": {
    "clause": "ErraticRankClause",
    "valueProperty": "rank",
    "valueIsList": false
  },
  "erraticRanks": {
    "clause": "ErraticRankClause",
    "valueProperty": "rank",
    "valueIsList": false
  },
  "erraticSuit": {
    "clause": "ErraticSuitClause",
    "valueProperty": "suit",
    "valueIsList": false
  },
  "erraticSuits": {
    "clause": "ErraticSuitClause",
    "valueProperty": "suit",
    "valueIsList": false
  },
  "voucher": {
    "clause": "VoucherClause",
    "valueProperty": "vouchers",
    "valueIsList": true
  },
  "vouchers": {
    "clause": "VoucherClause",
    "valueProperty": "vouchers",
    "valueIsList": true
  },
  "tag": {
    "clause": "TagClause",
    "valueProperty": "tags",
    "valueIsList": true
  },
  "tags": {
    "clause": "TagClause",
    "valueProperty": "tags",
    "valueIsList": true
  },
  "smallBlindTag": {
    "clause": "SmallBlindTagClause",
    "valueProperty": "tags",
    "valueIsList": true
  },
  "bigBlindTag": {
    "clause": "BigBlindTagClause",
    "valueProperty": "tags",
    "valueIsList": true
  },
  "boss": {
    "clause": "BossClause",
    "valueProperty": "bosses",
    "valueIsList": true
  },
  "bosses": {
    "clause": "BossClause",
    "valueProperty": "bosses",
    "valueIsList": true
  },
  "boosterPack": {
    "clause": "BoosterPackClause",
    "valueProperty": "packs",
    "valueIsList": true
  },
  "boosterPacks": {
    "clause": "BoosterPackClause",
    "valueProperty": "packs",
    "valueIsList": true
  },
  "pokerHand": {
    "clause": "PokerHandClause",
    "valueProperty": "pokerHands",
    "valueIsList": true
  },
  "pokerHands": {
    "clause": "PokerHandClause",
    "valueProperty": "pokerHands",
    "valueIsList": true
  },
  "startingDraw": {
    "clause": "StartingDrawClause",
    "valueProperty": "label",
    "valueIsList": false
  },
  "luckyMoney": {
    "clause": "LuckyMoneyClause",
    "valueProperty": "rolls",
    "valueIsList": true
  },
  "luckyMult": {
    "clause": "LuckyMultClause",
    "valueProperty": "rolls",
    "valueIsList": true
  },
  "misprintMult": {
    "clause": "MisprintMultClause",
    "valueProperty": "rolls",
    "valueIsList": true
  },
  "wheelOfFortune": {
    "clause": "WheelOfFortuneClause",
    "valueProperty": "rolls",
    "valueIsList": true
  },
  "wheelStaysFlipped": {
    "clause": "WheelStaysFlippedClause",
    "valueProperty": "rolls",
    "valueIsList": true
  },
  "glassDestroy": {
    "clause": "GlassDestroyClause",
    "valueProperty": "rolls",
    "valueIsList": true
  },
  "cavendishExtinct": {
    "clause": "CavendishExtinctClause",
    "valueProperty": "rolls",
    "valueIsList": true
  },
  "grosMichelExtinct": {
    "clause": "GrosMichelExtinctClause",
    "valueProperty": "rolls",
    "valueIsList": true
  },
  "spaceLevelup": {
    "clause": "SpaceLevelupClause",
    "valueProperty": "rolls",
    "valueIsList": true
  },
  "businessPayout": {
    "clause": "BusinessPayoutClause",
    "valueProperty": "rolls",
    "valueIsList": true
  },
  "parkingPayout": {
    "clause": "ParkingPayoutClause",
    "valueProperty": "rolls",
    "valueIsList": true
  },
  "bloodstoneTrigger": {
    "clause": "BloodstoneTriggerClause",
    "valueProperty": "rolls",
    "valueIsList": true
  },
  "and": {
    "clause": "AndClause",
    "valueProperty": "clauses",
    "valueIsList": true
  },
  "or": {
    "clause": "OrClause",
    "valueProperty": "clauses",
    "valueIsList": true
  }
} as const;

/** Clause class -> every key the loader maps on it (camelCase; unknown keys are rejected). */
export const CLAUSE_KEYS: Record<string, readonly string[]> = {
  "JokerClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "jokers",
    "edition",
    "stickers",
    "sources",
    "legendarySources"
  ],
  "CommonJokerClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "jokers",
    "edition",
    "stickers",
    "sources"
  ],
  "UncommonJokerClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "jokers",
    "edition",
    "stickers",
    "sources"
  ],
  "RareJokerClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "jokers",
    "edition",
    "stickers",
    "sources"
  ],
  "LegendaryJokerClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "jokers",
    "edition",
    "sources",
    "soulCardOnly",
    "soulEditionRolls"
  ],
  "PlanetCardClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "planets",
    "sources"
  ],
  "SpectralCardClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "spectrals",
    "sources"
  ],
  "TarotCardClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "tarots",
    "sources"
  ],
  "StandardCardClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "rank",
    "suit",
    "enhancement",
    "seal",
    "edition",
    "sources"
  ],
  "ErraticRankClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "rank"
  ],
  "ErraticSuitClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "suit"
  ],
  "VoucherClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "vouchers",
    "rolls"
  ],
  "TagClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "tags",
    "rolls"
  ],
  "SmallBlindTagClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "tags",
    "rolls"
  ],
  "BigBlindTagClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "tags",
    "rolls"
  ],
  "BossClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "bosses"
  ],
  "BoosterPackClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "packs",
    "rolls"
  ],
  "PokerHandClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "pokerHands",
    "rolls"
  ],
  "StartingDrawClause": [
    "label",
    "min",
    "max",
    "score",
    "antes",
    "rank",
    "suit"
  ],
  "LuckyMoneyClause": [
    "label",
    "min",
    "max",
    "score",
    "rolls",
    "with"
  ],
  "LuckyMultClause": [
    "label",
    "min",
    "max",
    "score",
    "rolls",
    "with"
  ],
  "MisprintMultClause": [
    "label",
    "min",
    "max",
    "score",
    "rolls",
    "mult"
  ],
  "WheelOfFortuneClause": [
    "label",
    "min",
    "max",
    "score",
    "rolls",
    "with"
  ],
  "WheelStaysFlippedClause": [
    "label",
    "min",
    "max",
    "score",
    "rolls",
    "with"
  ],
  "GlassDestroyClause": [
    "label",
    "min",
    "max",
    "score",
    "rolls",
    "with"
  ],
  "CavendishExtinctClause": [
    "label",
    "min",
    "max",
    "score",
    "rolls",
    "with"
  ],
  "GrosMichelExtinctClause": [
    "label",
    "min",
    "max",
    "score",
    "rolls",
    "with"
  ],
  "SpaceLevelupClause": [
    "label",
    "min",
    "max",
    "score",
    "rolls",
    "with"
  ],
  "BusinessPayoutClause": [
    "label",
    "min",
    "max",
    "score",
    "rolls"
  ],
  "ParkingPayoutClause": [
    "label",
    "min",
    "max",
    "score",
    "rolls"
  ],
  "BloodstoneTriggerClause": [
    "label",
    "min",
    "max",
    "score",
    "rolls"
  ],
  "AndClause": [
    "label",
    "min",
    "max",
    "score",
    "mode",
    "clauses"
  ],
  "OrClause": [
    "label",
    "min",
    "max",
    "score",
    "mode",
    "clauses"
  ]
};

/** "<ClauseClass>.<sources key>" -> every key the loader maps inside that sources block. */
export const SOURCE_KEYS: Record<string, readonly string[]> = {
  "JokerClause.sources": [
    "shopItems",
    "boosterPacks",
    "requireMegaPack",
    "judgement",
    "wraith",
    "riffRaff",
    "rareTag",
    "uncommonTag",
    "commonShopJokers",
    "uncommonShopJokers",
    "rareShopJokers",
    "allShopJokers"
  ],
  "JokerClause.legendarySources": [
    "boosterPacks",
    "arcanaPacks",
    "spectralPacks",
    "requireMegaPack"
  ],
  "CommonJokerClause.sources": [
    "shopItems",
    "boosterPacks",
    "requireMegaPack",
    "judgement",
    "wraith",
    "riffRaff",
    "rareTag",
    "uncommonTag",
    "commonShopJokers",
    "uncommonShopJokers",
    "rareShopJokers",
    "allShopJokers"
  ],
  "UncommonJokerClause.sources": [
    "shopItems",
    "boosterPacks",
    "requireMegaPack",
    "judgement",
    "wraith",
    "riffRaff",
    "rareTag",
    "uncommonTag",
    "commonShopJokers",
    "uncommonShopJokers",
    "rareShopJokers",
    "allShopJokers"
  ],
  "RareJokerClause.sources": [
    "shopItems",
    "boosterPacks",
    "requireMegaPack",
    "judgement",
    "wraith",
    "riffRaff",
    "rareTag",
    "uncommonTag",
    "commonShopJokers",
    "uncommonShopJokers",
    "rareShopJokers",
    "allShopJokers"
  ],
  "LegendaryJokerClause.sources": [
    "boosterPacks",
    "arcanaPacks",
    "spectralPacks",
    "requireMegaPack"
  ],
  "PlanetCardClause.sources": [
    "shopItems",
    "boosterPacks",
    "requireMegaPack"
  ],
  "SpectralCardClause.sources": [
    "shopItems",
    "boosterPacks",
    "sixthSense",
    "seance",
    "requireMegaPack",
    "etherealTag",
    "omenGlobe"
  ],
  "TarotCardClause.sources": [
    "shopItems",
    "boosterPacks",
    "emperor",
    "purpleSealOrEightBall",
    "charmTag",
    "requireMegaPack"
  ],
  "StandardCardClause.sources": [
    "shopItems",
    "boosterPacks",
    "requireMegaPack"
  ]
};

/** Enums/MotelyJokerSticker.cs — the one item enum motely-wasm does not export. */
export const MOTELY_JOKER_STICKER: readonly string[] = ["None","Eternal","Perishable","Rental"];
