import { init } from "@rewaffle/bootsharp-file-system";
// Assuming motely-wasm exposes Bootsharp APIs
// We need to pass the FileMounter export generated by Bootsharp
import * as motelyWasm from "motely-wasm";

export function initJamlFileSystem() {
  if (motelyWasm && (motelyWasm as any).Bootsharp && (motelyWasm as any).Bootsharp.FileSystem) {
    const fileMounter = (motelyWasm as any).Bootsharp.FileSystem.FileMounter;
    if (fileMounter) {
      init(fileMounter);
      return true;
    }
  }
  
  // Also try lowercase namespaces depending on how bootsharp generates it
  if (motelyWasm && (motelyWasm as any).bootsharp && (motelyWasm as any).bootsharp.fileSystem) {
    const fileMounter = (motelyWasm as any).bootsharp.fileSystem.fileMounter;
    if (fileMounter) {
      init(fileMounter);
      return true;
    }
  }
  
  console.warn("Could not initialize Jaml File System: Bootsharp.FileSystem.FileMounter not found in motely-wasm.");
  return false;
}
