import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const pkg = JSON.parse(readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const out = `// Generated by scripts/gen-version.mjs from package.json — do not edit.\nexport const JAML_UI_VERSION = "${pkg.version}";\n`;
writeFileSync(fileURLToPath(new URL("../src/version.ts", import.meta.url)), out);
