// AUTO-GENERATED — do not hand-edit.
//
// 149 alternate meanings of JAML, generated from the JAML.motds
// corpus (MOTD.md). Add new ones there and re-run `pnpm motd:emit`.

export const JAML_MOTDS: readonly string[] = Object.freeze([
  "Just Another Magic Link",
  "Jokers Always Make Luck",
  "Jimbo's Ante Management Lounge",
  "Jackpot Aces Meet Legends",
  "Just Add More Levels",
  "Jimbo Ate My Lunch",
  "Joker Addicts Monthly Letter",
  "Just Another Motely Lake",
  "Jimbo's Awful Messing-up Language",
  "Jealous Antes Make Losers",
  "Jambalaya And Mama's Laughter",
  "Jimbo And Motely? Lovely!",
  "Jimbo Approves My Luck",
  "Jimbo's Amazing Multiplier Locator",
  "Jolly Aces Make Legendaries",
  "Jackpot Ante Modifier Language",
  "Just Another Multiplier Legend",
  "Just Ace Me Lucky",
  "Java? Assembly?? Machine Language?!",
  "Just Another Markup Language",
  "JSON's Awesome Markup Lovechild",
  "YAML Already Made Lemonade",
  "Jolly Ante Manipulation Lab",
  "Just Another Motely Launcher",
  "Jokers Acquired, Multipliers Loaded",
  "Just Ante My Life",
  "Jumbled Assorted Microprocessor Luggage",
  "Jolly And Merry Love",
  "Jimbos Absolutely Magnificent Laughter",
  "Just Add More Legendaries",
  "Jokes And Memes, Literally",
  "Just Another Million Loops",
  "Join And Match Legendaries",
  "Juggling All Matching Loots",
  "Juiced And Massively Loaded",
  "Jetting At Maximum Lightspeed",
  "Jokes Are My Legacy",
  "Jesting About My Luck",
  "Joyful And Maybe Lucky",
  "Jokers, Antes, Mayhem, Loot",
  "Jimbo's Ante Modeling Language",
  "Jester Alchemy Markup Lore",
  "Jokers, Antes, Money, Luck",
  "Jimbo's Arcane Match Language",
  "Jackpot-Adjacent Miracle Logic",
  "Jumbo Ante Mystery List",
  "Jolly Antes, Magnificent Loot",
  "Joy And Mischief, Lovingly",
  "Just Adore My Little-language",
  "Justifiably Allergic to Made-up Lies",
  "Jimmy Ain't Mealy-mouthed, Listening",
  "Jimbo And Me, Long-haul",
  "Jokers, Antes, Multipliers, Legends",
  "Jubilant Aces, Maximum Love",
  "Jimbo's Anti-bullshit Marathon League",
  "Just A Mighty Lifeform",
  "Just A Meaning-Layer",
  "Jamlyzer Always Manifests Lenses",
  "Just A Mighty Little-joker",
  "Justice And Mustard Longdogs",
  "Join A Mining-pool, Lovingly",
  "Jimbo's Astronomically Massive Lottery",
  "Jokers Are Mathematically Lawful",
  "Just A Morning-ritual, Lovingly",
  "Juicing All Matching Lucky-cards",
  "Jobs Are Marked, Leased",
  "Just A Markup, Leveraged",
  "Joyfully Avoiding Manual Labor",
  "Jacked And Massively Leveraged",
  "Just Another Mega Lead-card",
  "Jumbled Aces, Mostly Lopsided",
  "Jimbo Adores My Lola",
  "Janky API, Mostly Loveable",
  "Jellyfish Are Mostly Liquid",
  "Jorts And Mismatched Loafers",
  "Jupiter Aligns Mercury's Lunar-cycle",
  "YAML Anagram? Mostly Lies",
  "Joyfully Annotating Motely's Lookups",
  "Just Add Motely, Limitless",
  "Jointly Auditing Motely's Ledger",
  "Jokers Argue, Multipliers Listen",
  "Jimbo Audits Marginal Luck",
  "Joker Algebra Made Legible",
  "Jittery Aces, Measured Losses",
  "Jimbo's Ante-Math: Lossless",
  "Joyfully Anti-sycophant, Mostly Lucid",
  "Just A Mirror-Layer",
  "Just A Magnet for Legendaries",
  "Jank Acknowledged, Marching Lovingly",
  "Jokers Argue; Mult Is Law",
  "Just A Manifest, Linted",
  "Juiced Aces, Multiplied Loudly",
  "Jolly Anarchists Marking Loot",
  "Jimbo's Arcana, Mapped Lightly",
  "Just A Markup, Load-bearing",
  "Jousting Antes, Mostly Lethal",
  "Jimbo And Motely: Lifers",
  "Joker Acquired, Mult Locked-in",
  "Just Ante, Manifest Legendary",
  "Jambalaya And Mama's Love",
  "Jigglebones And Memes, Laughter",
  "Jiggly Aquatic Micro-Legend",
  "Jukebox Awakens, Miraculously Loud",
  "Just Audit Me, Lovingly",
  "Jelly And Marmalade Lunchbox",
  "Just A Moment, Lola",
  "Jonkler-Approved Mischief License",
  "Just Another Midnight Legend",
  "Jolt Awake, Midnight Locksmith",
  "Jimbo Asked, Motely Listened",
  "Just Applied Math, Lovable",
  "Joyful Autopsy of My Losses",
  "Jettison All Mediocre Loadouts",
  "Jimbo's Advice: More Legendaries",
  "Jimbo's Arithmetic: Mostly Legit",
  "Jackdaws Adore My Lockpicks",
  "Juiced-up Antes, Minimal Losses",
  "Jigsaw of Antes, Masterfully Laid",
  "Juggle Antes, Master Life",
  "Joyride Across Motely's Lanes",
  "Jupiter's Ante, Mars' Luck",
  "Jazz Arrangement, Motely Largo",
  "Jab At Melancholy, Laugh",
  "Jesters Assemble, Money Laughs",
  "Jimbo's Almanac of Mult Lore",
  "Jackpots Arrive, Mortals Laugh",
  "Just Ask, Motely Listens",
  "Jimbo's Ace, My Lifeline",
  "Jailbreaking Ante Math, Legally",
  "Jamboree Always Means Love",
  "Jettison All Menace, Lovingly",
  "Jokers Are Made Locally",
  "Jimbo's Anti-barrel Manifesto, Literally",
  "Jettisoned All Meshes, Lastly",
  "Joy Around Mama's Lap",
  "Jokers Assemble, Mama's Looking",
  "Joker Arithmetic, Mercifully Legible",
  "Jubilant Antes, Merciful Losses",
  "Jimbo's Ante, Mama's Ledger",
  "Jesters And Marmalade, Lately",
  "Jitterbug Antes, Mambo Lessons",
  "Jelly, Ants, Marmalade, Ladybugs",
  "Joyous Alternative to Miserable Labels",
  "Jamboree And Mama's Lemonade",
  "Jimbo Absolutely Means Lola",
  "Just Ask Mama, Lovingly",
  "Jubilee At Motely's Landing",
  "Jokers Argue Merrily, Lovingly",
  "Just A Man, Loved",
]);
